login = "https://sso.icve.com.cn/prod-api/data/userLoginV2"
select_courses = "https://mooc.icve.com.cn/patch/zhzj/studentMooc_selectMoocCourse.action"
join_course = "https://mooc.icve.com.cn/patch/zhzj/dataCheck.action"
courseware = "https://course.icve.com.cn/learnspace/learn/learn/templateeight/courseware_index.action"
course_topic = "https://course.icve.com.cn/taolun/learn/courseTopicAction.action"